# Generated by Django 3.0.3 on 2020-02-26 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('[A-Za-z]{2,}'), django.core.validators.MinLengthValidator(2)])),
                ('msg', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
